apiVersion: v1
kind: Service
metadata:
    name: "saleorcoreservice-2394"
    labels:
        app: "saleorcoreservice-2394"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "saleorcoreservice-2394"